### ISSUE TITLE
The .apk does not work...

### ISSUE THREAD

**Issue by rodrigograca31** [personofinterestfan/samaritan#1]
The .apk on the repo does not work when I try to install it....

**Comment by rodrigograca31** [comment]
I was talking about the "samaritan.apk" on the repo root directory...
The one here works: https://github.com/personofinterestfan/samaritan/tree/master/samaritan/build/outputs/apk

**Comment by personofinterestfan** [comment]
Sorry about that. I'm still trying to figure out how to create a signed APK.

I'll try to get it working as soon as possible.

**Comment by personofinterestfan** [comment]
The signed APK in the root directory now works.

You may use this one, or continue using the debug apk.

**Comment by personofinterestfan** [comment]
The signed APK in the root directory now works.

You may use this one, or continue using the debug apk.

**Comment by rodrigograca31** [comment]
You could make a "folder link" to the one on the build folder, so that you don't have to move it every time you release a new version...
